Migration to nim 2.2.0 & some factor.
Narazaka/shioridll-nim pull request #4
Opened 2024-12-27 01:26 UTC by tukinami

nim 2.2.0でコンパイルが通らなくなっていたので、記述を変更いたしました。
また、テストとnim.cfgを追加しました。

2025-02-17 16:17 UTC, Narazaka commented
ぬ！見ます

2025-02-17 17:40 UTC, Narazaka commented
手元で確認したところnim 2.2.2で元のままでもmingw32, vccともにコンパイルが通りました。（nim.cfgだけ置いた）
コンパイルが通らないとのことですがどういった環境でしたでしょうか。

またこのコードでもnim v1系でコンパイル可能なので要求バージョンを上げすぎな気がします。（v0.xではテストしていません）
v0系にstdがあったか定かでないですが、v0.xにないならstdつけなくてもコンパイル通るので付けない方が良い気も

```
Nim Compiler Version 2.2.2 [Windows: amd64]
Compiled at 2025-02-06
```

2025-02-17 17:42 UTC, Narazaka commented
vccでやる際には逆にこちらが必要でしたので直しました。
https://github.com/Narazaka/shioridll-nim/commit/a28a4df0aff3266e4c01874ccbef1a9ff547e7da

2025-02-17 17:49 UTC, Narazaka commented
ちなみにshioriAllocするとこでlenに1足しているところはセグフォが起こるとコミットログにありますが、一応これはSHIORI/3.0の規格通りの実装のはずです。null終端でないことは保証されていないため。

2025-02-17 23:13 UTC, tukinami commented
検証ありがとうございます。
自分の環境について何一つ記述しておらず、申し訳ありません。
他の件検証いたしたいのですが、少し時間がかかりそうなので、とりいぞぎ自分の環境を記します。
Windows11上の、MINGW32にてコンパイルしています。
MINGW32は更新をしていますが、`nim`はPullRequestした当時から更新していません。
```
Nim Compiler Version 2.2.0 [Windows: amd64]
Compiled at 2024-10-02
Copyright (c) 2006-2024 by Andreas Rumpf

active boot switches: -d:release
```

2025-02-18 08:28 UTC, tukinami commented
コンパイルが通らない件を検証したところ、私のnimコンパイル環境の構築に不備があったことが判明いたしました。
環境を整え直した結果、コンパイルが通るようになりました。
お手数おかけして申し訳ありません。

環境を整え直しても、私の環境上でnimbleを用いてこのライブラリをインポートして作成したDLLを実行したときに生じるSegmentation Faultは続いています。
ですが、本題ではないと思われる上に、まだ修正できていない環境の問題があるかもしれない状態で続けるのは良くないと思うので、このまま閉めてもよろしいでしょうか？

この度は大変申し訳ありませんでした。よろしくお願いいたします。

2025-02-18 09:29 UTC, Narazaka requested changes

2025-02-18 09:29 UTC, Narazaka commented on shioridll.nim
> +  import std/winlean
ここはたぶん互換のためにそのままのほうがよさそう

2025-02-18 09:29 UTC, Narazaka commented on shioridll.nim
> +  var reth = shioriAlloc(sizeof(char) * (len[] + 1))
SHIORI/3.0規格を参照したらlength後に\0があってもよいとのことなのでOK

2025-02-18 09:29 UTC, Narazaka commented on shioridll.nimble
> +requires "nim >= 2.2.0"
変更不要

2025-02-18 09:29 UTC, Narazaka commented on test.nim
> +import std/unittest
いったんテストは別のファイルで担保したので不要

2025-02-18 10:39 UTC, Narazaka commented
型の警告等をなくす変更もあり、これはこれで有用だと思うので、変更点を絞って頂けたら取り込もうかと

2025-02-18 11:01 UTC, tukinami commented
承知いたしました。
ただ、試行錯誤しており、かつ私が今立て込んでいて時間が取れないので、申し訳ありませんが大分遅くなると思います。

2025-02-18 15:59 UTC, Narazaka commented
なるほど、それならこちらでちょっとチェリーピッキングしてみます

2025-02-18 16:01 UTC, merged

2025-02-19 10:25 UTC, tukinami commented
お手数おかけしました。ありがとうございます。

重ねてになりますが、この度は大変申し訳ありませんでした。